//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5420.
// 
#pragma warning disable 1591

namespace HotelMana.TEASOLUTIONDOTNETWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HotelManaDatabaseAccessBinding", Namespace="http://www.teasolution.net/soap/HotelManaDatabaseAccess")]
    public partial class HotelManaDatabaseAccess : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback saveGiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getGiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveLoaiPhongOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLoaiPhongOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLoaiPhongByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateLoaiPhongOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteLoaiPhongOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveKhachOperationCompleted;
        
        private System.Threading.SendOrPostCallback getKhachOperationCompleted;
        
        private System.Threading.SendOrPostCallback getKhachByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getKhachByCmndOperationCompleted;
        
        private System.Threading.SendOrPostCallback savePhongOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPhongOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPhongByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPhongByIdLoaiOperationCompleted;
        
        private System.Threading.SendOrPostCallback updatePhongOperationCompleted;
        
        private System.Threading.SendOrPostCallback deletePhongOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveThueOperationCompleted;
        
        private System.Threading.SendOrPostCallback getThueOperationCompleted;
        
        private System.Threading.SendOrPostCallback getThueByIdKhachOperationCompleted;
        
        private System.Threading.SendOrPostCallback getThueByCmndOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveApDungOperationCompleted;
        
        private System.Threading.SendOrPostCallback getApDungOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HotelManaDatabaseAccess() {
            this.Url = global::HotelMana.Properties.Settings.Default.HotelMana_TEASOLUTIONDOTNETWS_HotelManaDatabaseAccess;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event saveGiaCompletedEventHandler saveGiaCompleted;
        
        /// <remarks/>
        public event getGiaCompletedEventHandler getGiaCompleted;
        
        /// <remarks/>
        public event saveLoaiPhongCompletedEventHandler saveLoaiPhongCompleted;
        
        /// <remarks/>
        public event getLoaiPhongCompletedEventHandler getLoaiPhongCompleted;
        
        /// <remarks/>
        public event getLoaiPhongByIdCompletedEventHandler getLoaiPhongByIdCompleted;
        
        /// <remarks/>
        public event updateLoaiPhongCompletedEventHandler updateLoaiPhongCompleted;
        
        /// <remarks/>
        public event deleteLoaiPhongCompletedEventHandler deleteLoaiPhongCompleted;
        
        /// <remarks/>
        public event saveKhachCompletedEventHandler saveKhachCompleted;
        
        /// <remarks/>
        public event getKhachCompletedEventHandler getKhachCompleted;
        
        /// <remarks/>
        public event getKhachByIdCompletedEventHandler getKhachByIdCompleted;
        
        /// <remarks/>
        public event getKhachByCmndCompletedEventHandler getKhachByCmndCompleted;
        
        /// <remarks/>
        public event savePhongCompletedEventHandler savePhongCompleted;
        
        /// <remarks/>
        public event getPhongCompletedEventHandler getPhongCompleted;
        
        /// <remarks/>
        public event getPhongByIdCompletedEventHandler getPhongByIdCompleted;
        
        /// <remarks/>
        public event getPhongByIdLoaiCompletedEventHandler getPhongByIdLoaiCompleted;
        
        /// <remarks/>
        public event updatePhongCompletedEventHandler updatePhongCompleted;
        
        /// <remarks/>
        public event deletePhongCompletedEventHandler deletePhongCompleted;
        
        /// <remarks/>
        public event saveThueCompletedEventHandler saveThueCompleted;
        
        /// <remarks/>
        public event getThueCompletedEventHandler getThueCompleted;
        
        /// <remarks/>
        public event getThueByIdKhachCompletedEventHandler getThueByIdKhachCompleted;
        
        /// <remarks/>
        public event getThueByCmndCompletedEventHandler getThueByCmndCompleted;
        
        /// <remarks/>
        public event saveApDungCompletedEventHandler saveApDungCompleted;
        
        /// <remarks/>
        public event getApDungCompletedEventHandler getApDungCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.teasolution.net/service/tea_hotelmanager_database/ws.php/saveGia", RequestNamespace="http://www.teasolution.net/service", ResponseNamespace="http://www.teasolution.net/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string saveGia(string gia) {
            object[] results = this.Invoke("saveGia", new object[] {
                        gia});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void saveGiaAsync(string gia) {
            this.saveGiaAsync(gia, null);
        }
        
        /// <remarks/>
        public void saveGiaAsync(string gia, object userState) {
            if ((this.saveGiaOperationCompleted == null)) {
                this.saveGiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveGiaOperationCompleted);
            }
            this.InvokeAsync("saveGia", new object[] {
                        gia}, this.saveGiaOperationCompleted, userState);
        }
        
        private void OnsaveGiaOperationCompleted(object arg) {
            if ((this.saveGiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveGiaCompleted(this, new saveGiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.teasolution.net/service/tea_hotelmanager_database/ws.php/getGia", RequestNamespace="http://www.teasolution.net/service", ResponseNamespace="http://www.teasolution.net/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getGia(string not) {
            object[] results = this.Invoke("getGia", new object[] {
                        not});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getGiaAsync(string not) {
            this.getGiaAsync(not, null);
        }
        
        /// <remarks/>
        public void getGiaAsync(string not, object userState) {
            if ((this.getGiaOperationCompleted == null)) {
                this.getGiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetGiaOperationCompleted);
            }
            this.InvokeAsync("getGia", new object[] {
                        not}, this.getGiaOperationCompleted, userState);
        }
        
        private void OngetGiaOperationCompleted(object arg) {
            if ((this.getGiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getGiaCompleted(this, new getGiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.teasolution.net/service/tea_hotelmanager_database/ws.php/saveLoaiPhong" +
            "", RequestNamespace="http://www.teasolution.net/service", ResponseNamespace="http://www.teasolution.net/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string saveLoaiPhong(string tenloai) {
            object[] results = this.Invoke("saveLoaiPhong", new object[] {
                        tenloai});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void saveLoaiPhongAsync(string tenloai) {
            this.saveLoaiPhongAsync(tenloai, null);
        }
        
        /// <remarks/>
        public void saveLoaiPhongAsync(string tenloai, object userState) {
            if ((this.saveLoaiPhongOperationCompleted == null)) {
                this.saveLoaiPhongOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveLoaiPhongOperationCompleted);
            }
            this.InvokeAsync("saveLoaiPhong", new object[] {
                        tenloai}, this.saveLoaiPhongOperationCompleted, userState);
        }
        
        private void OnsaveLoaiPhongOperationCompleted(object arg) {
            if ((this.saveLoaiPhongCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveLoaiPhongCompleted(this, new saveLoaiPhongCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.teasolution.net/service/tea_hotelmanager_database/ws.php/getLoaiPhong", RequestNamespace="http://www.teasolution.net/service", ResponseNamespace="http://www.teasolution.net/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getLoaiPhong(string not) {
            object[] results = this.Invoke("getLoaiPhong", new object[] {
                        not});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getLoaiPhongAsync(string not) {
            this.getLoaiPhongAsync(not, null);
        }
        
        /// <remarks/>
        public void getLoaiPhongAsync(string not, object userState) {
            if ((this.getLoaiPhongOperationCompleted == null)) {
                this.getLoaiPhongOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLoaiPhongOperationCompleted);
            }
            this.InvokeAsync("getLoaiPhong", new object[] {
                        not}, this.getLoaiPhongOperationCompleted, userState);
        }
        
        private void OngetLoaiPhongOperationCompleted(object arg) {
            if ((this.getLoaiPhongCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLoaiPhongCompleted(this, new getLoaiPhongCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.teasolution.net/service/tea_hotelmanager_database/ws.php/getLoaiPhongB" +
            "yId", RequestNamespace="http://www.teasolution.net/service", ResponseNamespace="http://www.teasolution.net/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getLoaiPhongById(string iid_loai) {
            object[] results = this.Invoke("getLoaiPhongById", new object[] {
                        iid_loai});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getLoaiPhongByIdAsync(string iid_loai) {
            this.getLoaiPhongByIdAsync(iid_loai, null);
        }
        
        /// <remarks/>
        public void getLoaiPhongByIdAsync(string iid_loai, object userState) {
            if ((this.getLoaiPhongByIdOperationCompleted == null)) {
                this.getLoaiPhongByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLoaiPhongByIdOperationCompleted);
            }
            this.InvokeAsync("getLoaiPhongById", new object[] {
                        iid_loai}, this.getLoaiPhongByIdOperationCompleted, userState);
        }
        
        private void OngetLoaiPhongByIdOperationCompleted(object arg) {
            if ((this.getLoaiPhongByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLoaiPhongByIdCompleted(this, new getLoaiPhongByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.teasolution.net/service/tea_hotelmanager_database/ws.php/updateLoaiPho" +
            "ng", RequestNamespace="http://www.teasolution.net/service", ResponseNamespace="http://www.teasolution.net/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string updateLoaiPhong(string id_loai, string ten_loai) {
            object[] results = this.Invoke("updateLoaiPhong", new object[] {
                        id_loai,
                        ten_loai});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updateLoaiPhongAsync(string id_loai, string ten_loai) {
            this.updateLoaiPhongAsync(id_loai, ten_loai, null);
        }
        
        /// <remarks/>
        public void updateLoaiPhongAsync(string id_loai, string ten_loai, object userState) {
            if ((this.updateLoaiPhongOperationCompleted == null)) {
                this.updateLoaiPhongOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateLoaiPhongOperationCompleted);
            }
            this.InvokeAsync("updateLoaiPhong", new object[] {
                        id_loai,
                        ten_loai}, this.updateLoaiPhongOperationCompleted, userState);
        }
        
        private void OnupdateLoaiPhongOperationCompleted(object arg) {
            if ((this.updateLoaiPhongCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateLoaiPhongCompleted(this, new updateLoaiPhongCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.teasolution.net/service/tea_hotelmanager_database/ws.php/deleteLoaiPho" +
            "ng", RequestNamespace="http://www.teasolution.net/service", ResponseNamespace="http://www.teasolution.net/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string deleteLoaiPhong(string id_loai) {
            object[] results = this.Invoke("deleteLoaiPhong", new object[] {
                        id_loai});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void deleteLoaiPhongAsync(string id_loai) {
            this.deleteLoaiPhongAsync(id_loai, null);
        }
        
        /// <remarks/>
        public void deleteLoaiPhongAsync(string id_loai, object userState) {
            if ((this.deleteLoaiPhongOperationCompleted == null)) {
                this.deleteLoaiPhongOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteLoaiPhongOperationCompleted);
            }
            this.InvokeAsync("deleteLoaiPhong", new object[] {
                        id_loai}, this.deleteLoaiPhongOperationCompleted, userState);
        }
        
        private void OndeleteLoaiPhongOperationCompleted(object arg) {
            if ((this.deleteLoaiPhongCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteLoaiPhongCompleted(this, new deleteLoaiPhongCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.teasolution.net/service/tea_hotelmanager_database/ws.php/saveKhach", RequestNamespace="http://www.teasolution.net/service", ResponseNamespace="http://www.teasolution.net/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string saveKhach(string tenkhach, string cmnd) {
            object[] results = this.Invoke("saveKhach", new object[] {
                        tenkhach,
                        cmnd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void saveKhachAsync(string tenkhach, string cmnd) {
            this.saveKhachAsync(tenkhach, cmnd, null);
        }
        
        /// <remarks/>
        public void saveKhachAsync(string tenkhach, string cmnd, object userState) {
            if ((this.saveKhachOperationCompleted == null)) {
                this.saveKhachOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveKhachOperationCompleted);
            }
            this.InvokeAsync("saveKhach", new object[] {
                        tenkhach,
                        cmnd}, this.saveKhachOperationCompleted, userState);
        }
        
        private void OnsaveKhachOperationCompleted(object arg) {
            if ((this.saveKhachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveKhachCompleted(this, new saveKhachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.teasolution.net/service/tea_hotelmanager_database/ws.php/getKhach", RequestNamespace="http://www.teasolution.net/service", ResponseNamespace="http://www.teasolution.net/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getKhach(string not) {
            object[] results = this.Invoke("getKhach", new object[] {
                        not});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getKhachAsync(string not) {
            this.getKhachAsync(not, null);
        }
        
        /// <remarks/>
        public void getKhachAsync(string not, object userState) {
            if ((this.getKhachOperationCompleted == null)) {
                this.getKhachOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetKhachOperationCompleted);
            }
            this.InvokeAsync("getKhach", new object[] {
                        not}, this.getKhachOperationCompleted, userState);
        }
        
        private void OngetKhachOperationCompleted(object arg) {
            if ((this.getKhachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getKhachCompleted(this, new getKhachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.teasolution.net/service/tea_hotelmanager_database/ws.php/getKhachById", RequestNamespace="http://www.teasolution.net/service", ResponseNamespace="http://www.teasolution.net/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getKhachById(string id) {
            object[] results = this.Invoke("getKhachById", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getKhachByIdAsync(string id) {
            this.getKhachByIdAsync(id, null);
        }
        
        /// <remarks/>
        public void getKhachByIdAsync(string id, object userState) {
            if ((this.getKhachByIdOperationCompleted == null)) {
                this.getKhachByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetKhachByIdOperationCompleted);
            }
            this.InvokeAsync("getKhachById", new object[] {
                        id}, this.getKhachByIdOperationCompleted, userState);
        }
        
        private void OngetKhachByIdOperationCompleted(object arg) {
            if ((this.getKhachByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getKhachByIdCompleted(this, new getKhachByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.teasolution.net/service/tea_hotelmanager_database/ws.php/getKhachByCmn" +
            "d", RequestNamespace="http://www.teasolution.net/service", ResponseNamespace="http://www.teasolution.net/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getKhachByCmnd(string cm) {
            object[] results = this.Invoke("getKhachByCmnd", new object[] {
                        cm});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getKhachByCmndAsync(string cm) {
            this.getKhachByCmndAsync(cm, null);
        }
        
        /// <remarks/>
        public void getKhachByCmndAsync(string cm, object userState) {
            if ((this.getKhachByCmndOperationCompleted == null)) {
                this.getKhachByCmndOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetKhachByCmndOperationCompleted);
            }
            this.InvokeAsync("getKhachByCmnd", new object[] {
                        cm}, this.getKhachByCmndOperationCompleted, userState);
        }
        
        private void OngetKhachByCmndOperationCompleted(object arg) {
            if ((this.getKhachByCmndCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getKhachByCmndCompleted(this, new getKhachByCmndCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.teasolution.net/service/tea_hotelmanager_database/ws.php/savePhong", RequestNamespace="http://www.teasolution.net/service", ResponseNamespace="http://www.teasolution.net/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string savePhong(string id_loai, string tenphong) {
            object[] results = this.Invoke("savePhong", new object[] {
                        id_loai,
                        tenphong});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void savePhongAsync(string id_loai, string tenphong) {
            this.savePhongAsync(id_loai, tenphong, null);
        }
        
        /// <remarks/>
        public void savePhongAsync(string id_loai, string tenphong, object userState) {
            if ((this.savePhongOperationCompleted == null)) {
                this.savePhongOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsavePhongOperationCompleted);
            }
            this.InvokeAsync("savePhong", new object[] {
                        id_loai,
                        tenphong}, this.savePhongOperationCompleted, userState);
        }
        
        private void OnsavePhongOperationCompleted(object arg) {
            if ((this.savePhongCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.savePhongCompleted(this, new savePhongCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.teasolution.net/service/tea_hotelmanager_database/ws.php/getPhong", RequestNamespace="http://www.teasolution.net/service", ResponseNamespace="http://www.teasolution.net/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getPhong(string not) {
            object[] results = this.Invoke("getPhong", new object[] {
                        not});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getPhongAsync(string not) {
            this.getPhongAsync(not, null);
        }
        
        /// <remarks/>
        public void getPhongAsync(string not, object userState) {
            if ((this.getPhongOperationCompleted == null)) {
                this.getPhongOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPhongOperationCompleted);
            }
            this.InvokeAsync("getPhong", new object[] {
                        not}, this.getPhongOperationCompleted, userState);
        }
        
        private void OngetPhongOperationCompleted(object arg) {
            if ((this.getPhongCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPhongCompleted(this, new getPhongCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.teasolution.net/service/tea_hotelmanager_database/ws.php/getPhongById", RequestNamespace="http://www.teasolution.net/service", ResponseNamespace="http://www.teasolution.net/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getPhongById(string id) {
            object[] results = this.Invoke("getPhongById", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getPhongByIdAsync(string id) {
            this.getPhongByIdAsync(id, null);
        }
        
        /// <remarks/>
        public void getPhongByIdAsync(string id, object userState) {
            if ((this.getPhongByIdOperationCompleted == null)) {
                this.getPhongByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPhongByIdOperationCompleted);
            }
            this.InvokeAsync("getPhongById", new object[] {
                        id}, this.getPhongByIdOperationCompleted, userState);
        }
        
        private void OngetPhongByIdOperationCompleted(object arg) {
            if ((this.getPhongByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPhongByIdCompleted(this, new getPhongByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.teasolution.net/service/tea_hotelmanager_database/ws.php/getPhongByIdL" +
            "oai", RequestNamespace="http://www.teasolution.net/service", ResponseNamespace="http://www.teasolution.net/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getPhongByIdLoai(string id) {
            object[] results = this.Invoke("getPhongByIdLoai", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getPhongByIdLoaiAsync(string id) {
            this.getPhongByIdLoaiAsync(id, null);
        }
        
        /// <remarks/>
        public void getPhongByIdLoaiAsync(string id, object userState) {
            if ((this.getPhongByIdLoaiOperationCompleted == null)) {
                this.getPhongByIdLoaiOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPhongByIdLoaiOperationCompleted);
            }
            this.InvokeAsync("getPhongByIdLoai", new object[] {
                        id}, this.getPhongByIdLoaiOperationCompleted, userState);
        }
        
        private void OngetPhongByIdLoaiOperationCompleted(object arg) {
            if ((this.getPhongByIdLoaiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPhongByIdLoaiCompleted(this, new getPhongByIdLoaiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.teasolution.net/service/tea_hotelmanager_database/ws.php/updatePhong", RequestNamespace="http://www.teasolution.net/service", ResponseNamespace="http://www.teasolution.net/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string updatePhong(string id, string loai, string ten) {
            object[] results = this.Invoke("updatePhong", new object[] {
                        id,
                        loai,
                        ten});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updatePhongAsync(string id, string loai, string ten) {
            this.updatePhongAsync(id, loai, ten, null);
        }
        
        /// <remarks/>
        public void updatePhongAsync(string id, string loai, string ten, object userState) {
            if ((this.updatePhongOperationCompleted == null)) {
                this.updatePhongOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdatePhongOperationCompleted);
            }
            this.InvokeAsync("updatePhong", new object[] {
                        id,
                        loai,
                        ten}, this.updatePhongOperationCompleted, userState);
        }
        
        private void OnupdatePhongOperationCompleted(object arg) {
            if ((this.updatePhongCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updatePhongCompleted(this, new updatePhongCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.teasolution.net/service/tea_hotelmanager_database/ws.php/deletePhong", RequestNamespace="http://www.teasolution.net/service", ResponseNamespace="http://www.teasolution.net/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string deletePhong(string id) {
            object[] results = this.Invoke("deletePhong", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void deletePhongAsync(string id) {
            this.deletePhongAsync(id, null);
        }
        
        /// <remarks/>
        public void deletePhongAsync(string id, object userState) {
            if ((this.deletePhongOperationCompleted == null)) {
                this.deletePhongOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeletePhongOperationCompleted);
            }
            this.InvokeAsync("deletePhong", new object[] {
                        id}, this.deletePhongOperationCompleted, userState);
        }
        
        private void OndeletePhongOperationCompleted(object arg) {
            if ((this.deletePhongCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deletePhongCompleted(this, new deletePhongCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.teasolution.net/service/tea_hotelmanager_database/ws.php/saveThue", RequestNamespace="http://www.teasolution.net/service", ResponseNamespace="http://www.teasolution.net/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string saveThue(string id_phong, string id_khach, string den, string di) {
            object[] results = this.Invoke("saveThue", new object[] {
                        id_phong,
                        id_khach,
                        den,
                        di});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void saveThueAsync(string id_phong, string id_khach, string den, string di) {
            this.saveThueAsync(id_phong, id_khach, den, di, null);
        }
        
        /// <remarks/>
        public void saveThueAsync(string id_phong, string id_khach, string den, string di, object userState) {
            if ((this.saveThueOperationCompleted == null)) {
                this.saveThueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveThueOperationCompleted);
            }
            this.InvokeAsync("saveThue", new object[] {
                        id_phong,
                        id_khach,
                        den,
                        di}, this.saveThueOperationCompleted, userState);
        }
        
        private void OnsaveThueOperationCompleted(object arg) {
            if ((this.saveThueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveThueCompleted(this, new saveThueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.teasolution.net/service/tea_hotelmanager_database/ws.php/getThue", RequestNamespace="http://www.teasolution.net/service", ResponseNamespace="http://www.teasolution.net/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getThue(string not) {
            object[] results = this.Invoke("getThue", new object[] {
                        not});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getThueAsync(string not) {
            this.getThueAsync(not, null);
        }
        
        /// <remarks/>
        public void getThueAsync(string not, object userState) {
            if ((this.getThueOperationCompleted == null)) {
                this.getThueOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetThueOperationCompleted);
            }
            this.InvokeAsync("getThue", new object[] {
                        not}, this.getThueOperationCompleted, userState);
        }
        
        private void OngetThueOperationCompleted(object arg) {
            if ((this.getThueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getThueCompleted(this, new getThueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.teasolution.net/service/tea_hotelmanager_database/ws.php/getThueByIdKh" +
            "ach", RequestNamespace="http://www.teasolution.net/service", ResponseNamespace="http://www.teasolution.net/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getThueByIdKhach(string id_khach) {
            object[] results = this.Invoke("getThueByIdKhach", new object[] {
                        id_khach});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getThueByIdKhachAsync(string id_khach) {
            this.getThueByIdKhachAsync(id_khach, null);
        }
        
        /// <remarks/>
        public void getThueByIdKhachAsync(string id_khach, object userState) {
            if ((this.getThueByIdKhachOperationCompleted == null)) {
                this.getThueByIdKhachOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetThueByIdKhachOperationCompleted);
            }
            this.InvokeAsync("getThueByIdKhach", new object[] {
                        id_khach}, this.getThueByIdKhachOperationCompleted, userState);
        }
        
        private void OngetThueByIdKhachOperationCompleted(object arg) {
            if ((this.getThueByIdKhachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getThueByIdKhachCompleted(this, new getThueByIdKhachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.teasolution.net/service/tea_hotelmanager_database/ws.php/getThueByCmnd" +
            "", RequestNamespace="http://www.teasolution.net/service", ResponseNamespace="http://www.teasolution.net/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getThueByCmnd(string cm) {
            object[] results = this.Invoke("getThueByCmnd", new object[] {
                        cm});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getThueByCmndAsync(string cm) {
            this.getThueByCmndAsync(cm, null);
        }
        
        /// <remarks/>
        public void getThueByCmndAsync(string cm, object userState) {
            if ((this.getThueByCmndOperationCompleted == null)) {
                this.getThueByCmndOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetThueByCmndOperationCompleted);
            }
            this.InvokeAsync("getThueByCmnd", new object[] {
                        cm}, this.getThueByCmndOperationCompleted, userState);
        }
        
        private void OngetThueByCmndOperationCompleted(object arg) {
            if ((this.getThueByCmndCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getThueByCmndCompleted(this, new getThueByCmndCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.teasolution.net/service/tea_hotelmanager_database/ws.php/saveApDung", RequestNamespace="http://www.teasolution.net/service", ResponseNamespace="http://www.teasolution.net/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string saveApDung(string id_gia, string id_loai, string bdad, string ktad) {
            object[] results = this.Invoke("saveApDung", new object[] {
                        id_gia,
                        id_loai,
                        bdad,
                        ktad});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void saveApDungAsync(string id_gia, string id_loai, string bdad, string ktad) {
            this.saveApDungAsync(id_gia, id_loai, bdad, ktad, null);
        }
        
        /// <remarks/>
        public void saveApDungAsync(string id_gia, string id_loai, string bdad, string ktad, object userState) {
            if ((this.saveApDungOperationCompleted == null)) {
                this.saveApDungOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveApDungOperationCompleted);
            }
            this.InvokeAsync("saveApDung", new object[] {
                        id_gia,
                        id_loai,
                        bdad,
                        ktad}, this.saveApDungOperationCompleted, userState);
        }
        
        private void OnsaveApDungOperationCompleted(object arg) {
            if ((this.saveApDungCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveApDungCompleted(this, new saveApDungCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.teasolution.net/service/tea_hotelmanager_database/ws.php/getApDung", RequestNamespace="http://www.teasolution.net/service", ResponseNamespace="http://www.teasolution.net/service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getApDung(string not) {
            object[] results = this.Invoke("getApDung", new object[] {
                        not});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getApDungAsync(string not) {
            this.getApDungAsync(not, null);
        }
        
        /// <remarks/>
        public void getApDungAsync(string not, object userState) {
            if ((this.getApDungOperationCompleted == null)) {
                this.getApDungOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetApDungOperationCompleted);
            }
            this.InvokeAsync("getApDung", new object[] {
                        not}, this.getApDungOperationCompleted, userState);
        }
        
        private void OngetApDungOperationCompleted(object arg) {
            if ((this.getApDungCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getApDungCompleted(this, new getApDungCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void saveGiaCompletedEventHandler(object sender, saveGiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveGiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveGiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getGiaCompletedEventHandler(object sender, getGiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getGiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getGiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void saveLoaiPhongCompletedEventHandler(object sender, saveLoaiPhongCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveLoaiPhongCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveLoaiPhongCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getLoaiPhongCompletedEventHandler(object sender, getLoaiPhongCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLoaiPhongCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLoaiPhongCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getLoaiPhongByIdCompletedEventHandler(object sender, getLoaiPhongByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLoaiPhongByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLoaiPhongByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void updateLoaiPhongCompletedEventHandler(object sender, updateLoaiPhongCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateLoaiPhongCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateLoaiPhongCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void deleteLoaiPhongCompletedEventHandler(object sender, deleteLoaiPhongCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteLoaiPhongCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteLoaiPhongCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void saveKhachCompletedEventHandler(object sender, saveKhachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveKhachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveKhachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getKhachCompletedEventHandler(object sender, getKhachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getKhachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getKhachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getKhachByIdCompletedEventHandler(object sender, getKhachByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getKhachByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getKhachByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getKhachByCmndCompletedEventHandler(object sender, getKhachByCmndCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getKhachByCmndCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getKhachByCmndCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void savePhongCompletedEventHandler(object sender, savePhongCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class savePhongCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal savePhongCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getPhongCompletedEventHandler(object sender, getPhongCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPhongCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPhongCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getPhongByIdCompletedEventHandler(object sender, getPhongByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPhongByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPhongByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getPhongByIdLoaiCompletedEventHandler(object sender, getPhongByIdLoaiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPhongByIdLoaiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPhongByIdLoaiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void updatePhongCompletedEventHandler(object sender, updatePhongCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updatePhongCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updatePhongCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void deletePhongCompletedEventHandler(object sender, deletePhongCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deletePhongCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deletePhongCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void saveThueCompletedEventHandler(object sender, saveThueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveThueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveThueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getThueCompletedEventHandler(object sender, getThueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getThueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getThueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getThueByIdKhachCompletedEventHandler(object sender, getThueByIdKhachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getThueByIdKhachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getThueByIdKhachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getThueByCmndCompletedEventHandler(object sender, getThueByCmndCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getThueByCmndCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getThueByCmndCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void saveApDungCompletedEventHandler(object sender, saveApDungCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveApDungCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveApDungCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getApDungCompletedEventHandler(object sender, getApDungCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getApDungCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getApDungCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591